### PR TITLE
fix: workflow

### PR DESCRIPTION
**Pull request by kunal00000**

### CODE REVIEW

**Comment by DonKoko** [comment]
@kunal00000 i had to remove the playwright tests from main branch because of the issue as I couldnt deploy. I think when u made this branch you made it a copy of main so it doesnt have playwright tests. I think you should either enable them in thsi branch to see if it works and if not make a new PR from the previous branch you had, without updating it with main.

**Comment by kunal00000** [comment]
I think it will come if you approve it. I didn't update it with main.

**Comment by DonKoko** [comment]
Also I noticed this:
Screenshot 2023-09-08 at 17 43 35

Its not authorized but the tests ran.

Also if you want to know this is how it looks the approval screen:
Screenshot 2023-09-08 at 17 42 52

**Comment by DonKoko** [comment]
@kunal00000 I dont know if you can see the same as me so I am sharing:
Screenshot 2023-09-08 at 17 45 26

1. The tests seem to actually run before authorizing
2. Can you check if the playwright test is commented out in test.yml file cuz its not showing up here

**Review by DonKoko — APPROVED** [review]

**Comment by DonKoko** [comment]
@kunal00000 done.

**Pull request merged**
