### PR TITLE
feature: Bookings

### PR DESCRIPTION
**Pull request by DonKoko**
## Bookings related issues

- #326 
- #588 
- #563 
- #562

## Testing strategy:

Here we have a lot to test and lots of complex scenarios with edge cases. Here I am making a list of all the scenarios as presented in figma. Keep in mind that those scenarios are the main paths but for sure there are some cases which are not solved.
This list is for me to keep track of what I have done. Once something is ready for testing I will put it in the list below.

### Progress

- [x] Creating a booking and adding assets - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=14-50739&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Check out a booking with `Reserved` status - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1381-23764&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Checking in an `ongoing` booking - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=73-15543&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Remove an asset from a booking that is not `complete` or `archived` - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-51680&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [ ] Edit a booking with `ongoing` status - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1383-28158&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Remove an asset from a booking that is not `complete` or `archived` - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-51680&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] User tries to reserve a `draft` booking that includes assets that are not available - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2033-36931&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Showing unavailable assets when adding assets to booking - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=73-15542&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Check out a booking that includes assets with `checked out` or `overdue` status - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1396-161183&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Filter booking index for archived bookings - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-87296&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Making an asset unavailable for bookings - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1196-18494&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] self-service user creates a booking - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2013-16223&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Email notifications - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1626-158911&mode=design&t=UHzdJZ1otZUKYjfz-0)

### Ready to test:

Please write a comment and for each scenario you are testing make a checklist of bugs/issues you are reporting. That way we can keep track.

- [x] Creating a booking and adding assets - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=14-50739&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Check out a booking with `Reserved` status - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1381-23764&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Checking in an `ongoing` booking - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=73-15543&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Remove an asset from a booking that is not `complete` or `archived` - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-51680&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Remove an asset from a booking that is not `complete` or `archived` - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-51680&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] User tries to reserve a `draft` booking that includes assets that are not available - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2033-36931&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Showing unavailable assets when adding assets to booking - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=73-15542&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Check out a booking that includes assets with `checked out` or `overdue` status - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1396-161183&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Filter booking index for archived bookings - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=78-87296&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Making an asset unavailable for bookings - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1196-18494&mode=design&t=JHb1hbAu4FOQm3sw-0)
- [x] Email notifications - [link](https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=1626-158911&mode=design&t=UHzdJZ1otZUKYjfz-0)
- [x] Cancelling a booking ( can be done if booking has the status, Reserved, Ongoing or Overdue). All 3 states need to be tested

### CODE REVIEW

**Comment by mahendraHegde** [comment]
> hey @mahendraHegde . I noticed one thing I would like to change. I can see that `Booking` has its name not required and not unique. Can we please change it so name is required and unique.

I can make it unique, but making it required means, we cant have draft bookings, initially i remember @jurrejansen  asked for empty drafts, not sure if it changed now?

**Comment by DonKoko** [comment]
@mahendraHegde I was thinking we can just give them the name `Draft booking`, `Draft booking 1`, `Draft booking 2`, etc.

**Comment by DonKoko** [comment]
@mahendraHegde we have a report for some errors related to pg-boss. @hunar1312 said he sees this error a lot in his terminal:
image

**Comment by hunar1312** [comment]
hi @mahendraHegde @DonKoko, received the error below twice after working for few hours on shelf and on the browser I get `Unable to fetch`.
image

**Comment by DonKoko** [comment]
> hi @mahendraHegde @DonKoko, received the error below twice after working for few hours on shelf. image
> 
> on the browser I get image

This should be fixed now if you update your branch. Can you test it and let us know please.

**Comment by DonKoko** [comment]
@mahendraHegde reporting an issue with scheduler. When I try to reserve an asset I get this error:
```
TypeError: Cannot read properties of undefined (reading 'sendAfter')
    at scheduleNextBookingJob (/Users/donkoko/devs/shelf/app/app/modules/booking/service.server.ts:36:30)
    at upsertBooking (/Users/donkoko/devs/shelf/app/app/modules/booking/service.server.ts:177:9)
    at action23 (/Users/donkoko/devs/shelf/app/app/routes/_layout+/bookings.$bookingId.tsx:202:7)
    at Object.callRouteActionRR (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
    at callLoaderOrAction (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/router/router.ts:3778:16)
    at submit (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/router/router.ts:2923:16)
    at queryImpl (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/router/router.ts:2858:22)
    at Object.queryRoute (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/router/router.ts:2808:18)
    at handleDataRequestRR (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/server-runtime/dist/server.js:77:20)
    at requestHandler (/Users/donkoko/devs/shelf/app/node_modules/@remix-run/server-runtime/dist/server.js:51:18)
POST /bookings/clqcjequg0000omyhguy6ackh?_data=routes%2F_layout%2B%2Fbookings.%24bookingId 500 - - 687.319 ms
```

DOesnt happen every time, I am trying to figure out why and when it happens, but this is all the info I have so far.

**Comment by jurrejansen** [comment]
**Creating a booking and adding assets**
- [ ] Missing filters in Manage assets modal (for future reference)

**Checking in an ongoing booking**	
- [ ] When Ongoing booking surpasses it’s End date / time the status does not change into Overdue 

**Remove an asset from a booking that is not complete or archived** 
- [ ] Removing an asset directly from index via the Action icon / dropdown is currently not working
- [ ] After removing a few assets via Manage assets modal I click Save and an error occurs 

**User tries to reserve a draft booking that includes assets that are not available**
- [ ] After adding asset(s) with a Checked out status to a Draft booking I was still able to Reserve
- [ ] After adding asset(s) that are marked as ‘Unavailable for bookings’ to a draft booking I was still able to Reserve 

**Showing unavailable assets when adding assets to booking**
- [ ] Asset that are marked as 'Unavailable for bookings' should not appear even when filtering the assets on "Show all assets"

**Check out a booking that includes assets with checked out or overdue status** 
- [ ] ‘Includes unavailable assets’ label does not appear on booking in the bookings index when booking is in Reserved state, includes assets that have Checked out status and Start date / time has surpassed 

**Filter booking index for archived bookings** 
- [ ] Unable to test, archiving bookings via the Action dropdown button on booking page does not work yet

Mail notification
- [ ] Booking confirmation does not get sent

**Comment by DonKoko** [comment]
hey @mahendraHegde . Here is my end of the morning update based on my tests from this morning. I will update this further during the day when I have more info:

Okey, after taking a second look there is still some stuff that are not working for me. Let me give you a general update:

1. The updated singleton for `scheduler` was not working for me. `scheduler` would be undefined so my emails wont send and the schedules wont run. I believe this happens just in local, but hard to say. So in order to test i restored the code of `scheduler.server.ts` that you had before we tried to fix the bug that Hunar faced.
2. For some reason I cant get the reservation email to fire. The remiders for 1h on check-in and check-out seem to be firing but the reservation reminder is not firing at all. (`booking/service.server.ts:239`). I am still debugging that and trying to figure out what is going on
3. `worker.server.ts:48` - the function `getTimeRemainingMessage` for some reason is not working. It just returns an empty string or something. 
Screenshot 2023-12-20 at 10 12 47
 I still havent gotten to debugging this, I will send an update if needed.

**Comment by jurrejansen** [comment]
**[WIP] UI related bugs / improvements**

- [ ] Is there a reason this Div has min-width? Could be valuable real-estate when turns out more columns are needed
Screenshot 2023-12-21 at 13 19 56

**Comment by DonKoko** [comment]
Some fixes I deployed to test:

- Archiving now works
- You can now assign to 
- Fixed lots of hydration issues
- Fixed some cases that control when certain buttons need to be rendered
- Allowed assigning booking to workspace owner

**Comment by DonKoko** [comment]
>  Improvement: When a booking period is selected, assets that are currently checked out are shown. This is ok. To avoid the user feeling concerned about the item showing up in the list and thinking that this is a system error I suggest to iterate the text from "Asset is currently checked out
This asset is currently checked out. Once it gets returned you will be able to check it out again" to "Asset is currently checked out
This asset is currently checked out as part of another booking (%booking name%/link) and should be available for your selected date range period".

This is not that easy at all and I would like to leave it for a second stage. In this view we have so many cases and options so we actually on returned the bookings that overlap during that period and we would need to make some big modifications to the queries to be able to know which booking is there if its not within the current period.

**Comment by jurrejansen** [comment]
WIP

**Remove an asset from a booking that is not complete or archived**

- [ ] After removing an asset from an Ongoing / Overdue booking the assets still appears as Checked out in the asset index
https://github.com/Shelf-nu/shelf.nu/assets/76112272/2c8cac6c-a224-4904-b9b7-28b8cb487444

- [ ] After removing an asset from Ongoing / Overdue booking and then deleting the booking. When creating a new booking and opening the Manage asset modal the asset that was removed from the intitial booking is showing the 'Checked out' label  when they're actually not
https://github.com/Shelf-nu/shelf.nu/assets/76112272/e8dd4ce2-d066-47a2-a599-ee4b0ac9fed0

**User tries to reserve a draft booking that includes assets that are not available**

**Comment by DonKoko** [comment]
Doing permissions for Self Service users. We need to go to all routes and adjust the permissions. Here is a list of all routes so we can keep track:

**Root:**

- [ ] filename.txt
- [ ] healthcheck.tsx
- [ ] qr+

**./_auth+:**

- [ ] _auth.tsx
- [ ] accept-invite.$inviteId.tsx
- [ ] forgot-password.tsx
- [ ] join.tsx
- [ ] login.tsx
- [ ] logout.tsx
- [ ] oauth.callback.tsx
- [ ] resend-email-confirmation.tsx
- [ ] reset-password.tsx
- [ ] send-magic-link.tsx
- [ ] verify-email.tsx

**./_layout+:**

- [ ] $.tsx
- [ ] _layout.tsx
- [ ] admin-dashboard+
- [ ] assets.$assetId.duplicate.tsx
- [ ] assets.$assetId.give-custody.tsx
- [ ] assets.$assetId.note.tsx
- [ ] assets.$assetId.qr.tsx
- [ ] assets.$assetId.release-custody.tsx
- [ ] assets.$assetId.tsx
- [ ] assets.$assetId.update-location.tsx
- [ ] assets.$assetId_.edit.tsx
- [ ] assets._index.tsx
- [ ] assets.export.$fileName[.csv].tsx
- [ ] assets.import.tsx
- [ ] assets.new.tsx
- [ ] assets.tsx
- [ ] bookings.$bookingId.add-assets.tsx
- [ ] bookings.$bookingId.tsx
- [ ] bookings._index.tsx
- [ ] bookings.new.tsx
- [ ] bookings.tsx
- [ ] categories.$categoryId_.edit.tsx
- [ ] categories.new.tsx
- [ ] categories.tsx
- [ ] dashboard.tsx
- [ ] locations.$locationId.add-assets.tsx
- [ ] locations.$locationId.tsx
- [ ] locations.$locationId_.edit.tsx
- [ ] locations._index.tsx
- [ ] locations.new.tsx
- [ ] locations.tsx
- [ ] settings.account.tsx
- [ ] settings.custom-fields.$fieldId_.edit.tsx
- [ ] settings.custom-fields.index.tsx
- [ ] settings.custom-fields.new.tsx
- [ ] settings.custom-fields.tsx
- [ ] settings.general.tsx
- [ ] settings.index.tsx
- [ ] settings.subscription.customer-portal.tsx
- [ ] settings.subscription.tsx
- [ ] settings.team.add-member.tsx
- [ ] settings.team.invite-user.tsx
- [ ] settings.team.tsx
- [ ] settings.tsx
- [ ] settings.workspace.$workspaceId.edit.tsx
- [ ] settings.workspace.index.tsx
- [ ] settings.workspace.new.tsx
- [ ] settings.workspace.tsx
- [ ] tags.$tagId_.edit.tsx
- [ ] tags.new.tsx
- [ ] tags.tsx

**./_layout+/admin-dashboard+:**

- [ ] $userId.tsx
- [ ] _layout.tsx
- [ ] announcements.new.tsx
- [ ] announcements.tsx
- [ ] org.$organizationId.tsx
- [ ] users.tsx

**./_welcome+:**

- [ ] _layout.tsx
- [ ] onboarding.tsx
- [ ] welcome.tsx

**./api+:**

- [ ] $organizationId.qr-codes[.zip].ts
- [ ] admin.export-org-assets.$organizationId.$fileName[.csv].tsx
- [ ] admin.import-org-assets.$organizationId.tsx
- [ ] asset.refresh-main-image.ts
- [ ] client-notification.ts
- [ ] image.$imageId.ts
- [ ] oss-friends.ts
- [ ] public-stats.ts
- [ ] sse.notification.ts
- [ ] stripe-webhook.ts
- [ ] user.change-current-organization.ts
- [ ] user.prefs.dismiss-support-banner.ts
- [ ] user.prefs.minimized-sidebar.ts
- [ ] user.prefs.skip-onboarding-checklist.ts
- [ ] user.prefs.upload-user-photo.ts
- [ ] utils.parse-markdown.ts

**./qr+:**

- [ ] $qrId.tsx
- [ ] $qrId_.contact-owner.tsx
- [ ] $qrId_.link.tsx
- [ ] $qrId_.not-logged-in.tsx
- [ ] route.tsx

**Comment by jurrejansen** [comment]
WIP

SELF-SERVICE

- [ ] When inviting a new user as an Administrator or Owner user I am able to assign the new user an Owner role which should not be possible

Screenshot 2024-01-12 at 11 50 36

- [ ] As a Self-service user I am still able to see the Custodian column in the asset index which should not be the case

Screenshot 2024-01-12 at 12 06 55

**Comment by DonKoko** [comment]
>  In the Custodian column in the asset index it is not showing the full name of the custodian but instead it is showing whatever is before the @ of the users email address

Okey so this happens because when you create an invite, before the user accepts it we have the NRM for it and we give it the name of the first part of the email. Once they accept we update the name, so we have 1 case when it can show the username.

>  In the Custodian column in the asset index it is not showing the full name of the custodian but instead it is showing whatever is before the @ of the users email address

That seems like a very edge case which i dont think we should handle now.


The rest is done and will be deployed in a bit. I will let you know when its deployed.

**Comment by DonKoko** [comment]
>  The assets that are already booked during the booking period are hidden and have a warning label indicating this. However the warning labels disappears after checking them

I fixed this but I am a bit unsure if it will not open other issues.

**Comment by jurrejansen** [comment]
WIP

- [ ] We need a ‘Check-in reminder’ mail when a booking gets checked out after the End date / time. Currently the mail is quite weird when this happens. This example is when check-out happened 44 minutes after End date / time. “Your booking was due for check-in 44 minutes ago”. Not a real case but it can happen.

Your booking is due for checkin in 44 minutes minutes

- [ ] Assets marked as 'Unavailable for bookings' are visible for Self-service users in the asset index which shouldn't be the case

Screenshot 2024-01-15 at 17 52 24

- [ ] A Self-service user is able to filter on All assets when using Asset manage modal which means they’re able to book assets that are already booked during the same booking period. Missed this in the scenario, but I think we should let Self-service users only filter on Hide Unavailable so they cannot cause double bookings. Then only Administrators will have the ability to create double bookings. This will also make sure Self-service are unable to see assets marked as Unavailable for bookings

https://github.com/Shelf-nu/shelf.nu/assets/76112272/c72455bf-aad7-42ca-94f0-9810285e475f

Or, we...


- [ ] 'Already booked' warning label appears when it shouldn't. It is showing because I am adding assets to the current booking which of course has the same booking period. Also, technically the asset is not 'Already booked' because the booking is still in a Reserved state. But not sure how this warning label is being handled.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/9c92cfc8-5593-43b3-ac2d-72949523025d

**Comment by jurrejansen** [comment]
MOBILE FRONT-END

- [ ] Can we vertically stack Search and Filter components and make them full width
Screenshot 2024-01-18 at 14 50 30

- [ ] Can we switch up H1 + Status section and Button section in Header component? Preferably this happens globally across the app so maybe better to address in a UI changes follow up issue

- [ ]  If we remove the left and right padding for the elements containing the fields for Name, Booking period and Custodian we can save some horizontal screen real estate

Screenshot 2024-01-18 at 14 53 59

- [ ] Manage assets modal is not mobile responsive

https://github.com/Shelf-nu/shelf.nu/assets/76112272/a3356314-02d6-468f-af0d-33317b1f65c6

**Comment by DonKoko** [comment]
I have implemented 2 of the points.
The rest are global changes that require too much work to be implemented in this branch. Should move them to a general issue for mobile improvements

**Comment by jurrejansen** [comment]
- [ ] 'Already booked' label showing in asset index located in booking area when 'Checked out' label should be showing like it is in the Manage assets modal

https://github.com/Shelf-nu/shelf.nu/assets/76112272/c7f7c56c-bde6-44cf-a500-8ba8da6cb2fb

Additionally, this means the wrong tool tip is also showing on the disabled Reserve button

Screenshot 2024-01-19 at 14 08 42

**Comment by DonKoko** [comment]
@jurrejansen solved 1 of the comments, the hard one. Also

>  Additionally, when configuring booking we're using the 24-hour and DD/MM/YYYY time / date format. In the booking index we're using the 12-hour and MM/DD/YY time / date format. Maybe not for now, as we have not yet implemented the settings for this. There was talk about potentially syncing it with device settings.

This is tricky. Here is how it works for me now.

1. Safari -they are consistent and using AM/PM style - I would assume this comes from the browser
2. FF - Input uses 24h style, index uses AM/PM style - This is just wacky
3. Chrome - both use 24h style and are consistent - I would assume this comes from system

**Comment by jurrejansen** [comment]
- [ ] Page does not exist error when closing Manage assets modal

https://github.com/Shelf-nu/shelf.nu/assets/76112272/8712e552-d713-45dd-8d96-80ce4dabe7d7

- [ ]  This one returned:  'Already booked' warning label appears in Manage assets modal when it shouldn't. It is showing because I am adding assets to the current booking which of course has the same booking period. Also, technically the asset is not 'Already booked' because the booking is still in a Draft state. But not sure how this warning label is being handled.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/9d1bad22-bfa6-491d-b154-dda95363d149

- [ ] Additionally, after clicking Reserve it took very long (as seen in video) and ended up on Unexpected error screen (probably cause of low speeds of testapp tho)

- [ ] 'Checked out' warning label is showing on assets in index of booking for which the assets are checked out. This doesn't make sense

https://github.com/Shelf-nu/shelf.nu/assets/76112272/1cda895a-b8ed-41fa-8347-1a7a54a9eb5b

- [ ] If we want to follow designs the 'checked out' warning label should say 'Unavailable' instead. The logic of when the label should show in described in the annotations under design
Screenshot 2024-01-22 at 18 05 34
Screenshot 2024-01-22 at 18 05 10

**Comment by jurrejansen** [comment]
- [ ] When configuring a booking and clicking save, additional Draft bookings get created. Sometimes 1, sometimes 2 additional ones that shouldn't have been created
https://github.com/Shelf-nu/shelf.nu/assets/76112272/1927176b-6175-46c7-9e46-9516e8c0fd01

Sorry to suggest this late in testing but...

- [ ] Can we send user back to booking index after performing actions like Reserve, Check-out, Check-in, Delete and Archive. I think in 90% of the cases they'll prefer this over staying on the individual booking page. We'll just have to make sure the notification works consistently informing them the action was successful. In my experience the notifications consistently work

**Pull request merged**
