### PR TITLE
enabled clearing location on edit page

### LINKED ISSUE #413: [Feature request]: Clear location
### Contact Details

_No response_

### Is your feature request related to a problem? Please describe?

At the moment, if you go to the edit view of an asset, you cannot clear the current location: 
Screenshot 2023-10-02 at 13 52 23

### Describe the solution you'd like

A link/button somwhere in the dropdown or just anywhere in the view that allows to remove the location.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hunar1312**
resolves #413

### CODE REVIEW

**Review by DonKoko — COMMENTED** [review]
It worked visually very nice but didn't actually work. The location stayed the same after saving. 

I can see in the form data that `newLocationId` is empty but I think you might have to adjust the action as well. Maybe type mismatch?

**Comment by carlosvirreira** [comment]
I tested this (safari, iPhone)

Like the position of the 'clear box' 

I have an issue, when I close it (remove it) - get presented my custom fields. 

Even if I add data, and I get a successful toast. The location persists and going through the edit process shows again the same state as when I started.

**Comment by hunar1312** [comment]
Hi @DonKoko @carlosvirreira, the issues you mentioned are fixed now.

**Comment by carlosvirreira** [comment]
Awesome, happy to test this again.

**Review by DonKoko — APPROVED** [review]

**Pull request merged**
