### PR TITLE
[Improvement]: Add standalone image build

### PR DESCRIPTION
**Pull request by anatolinicolae**
This PR targets self-hosted deployments, making it easier to run the app via Docker and fixing a potential reputation issue for outbound emails.

- Fix `start.sh`, making it executable and properly defining an interpreter
- Add standalone image build, pushing it to repo's Packages section (ghcr.io)
- ~~Fix FROM header for sent emails, introducing a new env var `SMTP_FROM`~~

> [!NOTE]
> Having `no-reply@shelf.nu` hardcoded can potentially hurt self-hosted installs as outbound domain will most likely be mismatched, sending emails from a different host on behalf of another one. This PR makes it customizable so end-users can set their own.

### CODE REVIEW

**Review by DonKoko — COMMENTED** [review]
Can you please remove the SMTP changes. I already tested the approach you did but it doesn't work exactly like this due to syntax required in the `from` field for emails. 
Anyways this is solved on main so you can remove it from the PR. I am reviewing the rest now. Dont have much docker experience so I need to consult with someone.

**Comment by anatolinicolae** [comment]
Removed that commit but just to clarify my implementation:
- the env var `SMTP_FROM="Shelf <noreply@example.com>"` contained **the whole FROM part**, the name and the address;
- at runtime it would be used when properly set, otherwise defaulted to hardcoded shelf.nu address.

Although your approach works too, mine would've given more customization freedom by allowing full control on how that is sent out.

**Comment by anatolinicolae** [comment]
Docker run example:

```sh
docker run -d \
  --name "shelf" \
  -e 'DATABASE_URL=postgres://postgres:{POSTGRES_PASSWORD}@db.{YOUR_INSTANCE_NAME}.supabase.co:5432/postgres' \
  -e 'SUPABASE_ANON_PUBLIC=ANON_PUBLIC' \
  -e 'SUPABASE_SERVICE_ROLE=SERVICE_ROLE' \
  -e 'SUPABASE_URL=https://{YOUR_INSTANCE_NAME}.supabase.co' \
  -e 'SESSION_SECRET=super-duper-s3cret' \
  -e 'SERVER_URL=http://localhost:3000' \
  -e 'MAPTILER_TOKEN=maptiler-token' \
  -e 'SMTP_HOST=mail.example.com' \
  -e 'SMTP_USER=some-email@example.com' \
  -e 'SMTP_PWD=super-safe-passw0rd' \
  -p 3000:8080 \
  --restart unless-stopped \
  ghcr.io/thundersquared/shelf:latest
```

**Comment by anatolinicolae** [comment]
Image now supports ARM too:
- Linux / Pine A64
  ```sh
  root@DietPi:~#
  docker run -it --rm --entrypoint /usr/bin/uname ghcr.io/thundersquared/shelf:latest -a
  Linux 77ae434f8fe9 6.1.63-current-sunxi64 #1 SMP Mon Nov 20 10:52:19 UTC 2023 aarch64 GNU/Linux
  ```
- macOS / M1 Max
  ```sh
  ❯ ~
  docker run -it --rm --platform linux/arm64 --entrypoint /usr/bin/uname ghcr.io/thundersquared/shelf:latest -a
  Linux 7a9dff819847 6.5.13-orbstack-00122-g57b8027e2387 #1 SMP Tue Feb  6 07:48:26 UTC 2024 aarch64 GNU/Linux
  ```

**Review by DonKoko — APPROVED** [review]
Merging to branch `standalone-docker` to do some testing on staging server.

**Pull request merged**
