### PR TITLE
feat: 369 feature request change data scoping to organization instead of user

### PR DESCRIPTION
**Pull request by DonKoko**

### CODE REVIEW

**Comment by DonKoko** [comment]
@mahendraHegde did a kinda big update. Here is the commit: https://github.com/Shelf-nu/shelf.nu/pull/414/commits/dd1ec5af7ca1b6973f127ee2a44e433aaadd886d
- created workspaces index
- created workspace page
- moved around some fetching functions

Next for me is creating the workspace/new page

**Comment by DonKoko** [comment]
hey @mahendraHegde. I have made progress on the route that validates the invite, however I have noticed something that I need some help with. Could you please check this TODO i did and solve it? 
https://github.com/Shelf-nu/shelf.nu/pull/414/files#diff-c54d998476cb16e1478f028dd1681fa9d5a2c877d094fc8a029967b7f5ea1efeR129-R132

**Comment by DonKoko** [comment]
@jurrejansen something I realized. In the workspaces index, I think its good if we can somehow visualize the difference between workspaces you have been added to and workspaces you own. Could you please update the design to include that.

**Comment by DonKoko** [comment]
hey @mahendraHegde. When working on the organizations I noticed something related to the Image model.
So we usually check if the image belongs to the user before we can display it, so we dont leak private images of users, however we have an issue now. If I am added to an organization I cant see its image because its userId is of the person who created the org.
Can you please add a relation between Image and Organization and make it work like with the other models? Then I can change the logic a bit in the loader (https://github.com/Shelf-nu/shelf.nu/blob/main/app/routes/api%2B/image.%24imageId.ts#L20) so its allowed to be viewed by anyone in the organization.

We will have the same issue for locations as well as there we manage images the same way.

**Comment by DonKoko** [comment]
Some stuff that are pending and we need to discuss:

- [ ] When I accept an invite, the Role I am giving within the organization is `OWNER` instead of `ADMIN`
- [ ] I have an issue that I invited a user, then I revoked their access and I cannot anymore get the teamMember entry. I am quite confused with this one so I need to show you.

**Comment by DonKoko** [comment]
There is an issue that I am having some trouble figuring out.
When sending an invite for a user I get one of two things happening:
1. I get a timeout message - the invite seems to still be created but no email is received so maybe its the sendEmail that times out.
2. I get an error "Greeting never received". No idea where this error comes from

**Comment by jurrejansen** [comment]
Here are some things I found.

- [ ] * After accepting invite and creating an account I get redirected to my Personal workspace instead of the workspace I was invited to
- [ ] * After getting revoked from Workspace, while still in workspace and not refreshing, you click Assets and you get ‘undefined’s inventory’
- [ ] * When inviting a NRM to make it a user, using the same email that already is attached to an existing user there is no error. The invitation mail will arrive in the mail box of the used email. After clicking / accepting, the NRM just gets merged with the existing account and nothing really breaks I think. But I think we should give the user an error when trying to use an email that is already attached to a user.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/7a1b7494-e3d3-4a8d-87a1-657bcb2364a0

- [ ] * Would be nice to style these tables the same way regarding min width of the tables. Or whatever causes them not to be the same width in this particular window size

Screenshot 2023-10-27 at 15 12 24

- [ ] * You can invite NRMs when in a personal workspace. When clicking the link in invitation mail from mail address that don’t has an account results in error

https://github.com/Shelf-nu/shelf.nu/assets/76112272/6686fdd1-66bb-432e-bffb-5cfe7bf9d9cb

- [ ] * Not a big deal. Responsiveness of Workspace, Team and NRM tables could be improved. Can we lose some columns maybe? Location maybe

Screenshot 2023-10-27 at 15 28 13

NOT RELATED TO TEAMS

- [ ] * When importing a CSV when on Team workspace, assets get added to Personal workspace

**Comment by DonKoko** [comment]
hey @mahendraHegde . Jurre did some testing and reported some stuff. Can you take a look at this please:


> - If you have a custom field on PERSONAL it gets shown on TEAM on EDIT (This works the other way around too, on my team space I can add a field and it shows up on personal. Adding the required text results in an error)
> - When inviting a NRM to make it a user, using the same email that already is attached to an existing user there is no error. The invitation mail will arrive in the mail box of the used email. After clicking / accepting, the NRM just gets merged with the existing account and nothing really breaks I think. But I think we should give the user an error when trying to use an email that is already attached to a user. 

FOr the second one I think he means within this workspace you can invite 2 seperate team mebers linked to the same user. He added a screenshot as well.

**Comment by mahendraHegde** [comment]
> hey @mahendraHegde . Jurre did some testing and reported some stuff. Can you take a look at this please:
> 
> > * If you have a custom field on PERSONAL it gets shown on TEAM on EDIT (This works the other way around too, on my team space I can add a field and it shows up on personal. Adding the required text results in an error)
> > * When inviting a NRM to make it a user, using the same email that already is attached to an existing user there is no error. The invitation mail will arrive in the mail box of the used email. After clicking / accepting, the NRM just gets merged with the existing account and nothing really breaks I think. But I think we should give the user an error when trying to use an email that is already attached to a user.
> 
> FOr the second one I think he means within this workspace you can invite 2 seperate team mebers linked to the same user. He added a screenshot as well.

https://github.com/Shelf-nu/shelf.nu/pull/414#issuecomment-1783138022 should fix point 2, im working on point 1

**Comment by jurrejansen** [comment]
- [ ] After getting revoked from Workspace, while still in workspace and not refreshing, you click Assets and you get redirected to Personal workspace but the Workspace select shows nothing. I know this is a temporary fix but just sharing what I experienced

Screenshot 2023-10-30 at 15 26 38

- [ ] Hide 'Invite user' option for NRM's when in Personal workspace

Screenshot 2023-10-30 at 15 31 02

- [ ] In the Workspaces table, Owner badges with avatar seem broken

Screenshot 2023-10-30 at 15 45 12

**Comment by mahendraHegde** [comment]
> hey @mahendraHegde . Jurre did some testing and reported some stuff. Can you take a look at this please:
> 
> > * If you have a custom field on PERSONAL it gets shown on TEAM on EDIT (This works the other way around too, on my team space I can add a field and it shows up on personal. Adding the required text results in an error)
> > * When inviting a NRM to make it a user, using the same email that already is attached to an existing user there is no error. The invitation mail will arrive in the mail box of the used email. After clicking / accepting, the NRM just gets merged with the existing account and nothing really breaks I think. But I think we should give the user an error when trying to use an email that is already attached to a user.
> 
> FOr the second one I think he means within this workspace you can invite 2 seperate team mebers linked to the same user. He added a screenshot as well.

fix for point 1 https://github.com/Shelf-nu/shelf.nu/pull/511

**Comment by DonKoko** [comment]
- [ ] Login after receiving invite to a new user - we need to set the current org to the one from the invite with the new approach

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira the last points of the feedback are solved. I am just doing emails now but those changes are being deployed so you can test them.

**Comment by DonKoko** [comment]
- [ ] On onboarding flow, we are not showing the error for unique username - reported by @rphlmr

**Pull request merged**
