### PR TITLE
Improvements in workflow

### PR DESCRIPTION
**Pull request by kunal00000**
Refactor- 
- Deploy workflow will only run on `push` trigger (along with tests).
- Passed secrets to tests called by Deploy.
- Remove duplicate tests from Deploy.
- Remove undeclared environment.

### CODE REVIEW

**Review by DonKoko — COMMENTED** [review]
Okey that seems good to me. Lets test this further.

**Comment by DonKoko** [comment]
One strange this I don't understand is this: 
Screenshot 2023-09-07 at 14 53 15

Anyways I will merge the commit, so we can test it and lets continue with talking about it on the issue itself.

**Comment by kunal00000** [comment]
Yes, this is strange 
> One strange this I don't understand is this:
Also, I guess it ran without anybody's permission. Did you add some users to external environment who can review and allow tests to run.

**Comment by kunal00000** [comment]
@DonKoko . Ping me once you merge this one.

**Comment by DonKoko** [comment]
@kunal00000 its merged. I believe this is the correct action: https://github.com/Shelf-nu/shelf.nu/actions/runs/6109457348
Screenshot 2023-09-07 at 15 07 13

**Comment by kunal00000** [comment]
Yes, seems correct.

**Comment by kunal00000** [comment]
@DonKoko . I feel that we can remove push trigger in Test PR from Fork as it will be running automatically via Deploy.

**Pull request merged**
